name: "RSpec Test Suite"
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu]
        ruby:
          - 2.0.0-p648
          - 2.1.0
          - 2.2.0
          - 2.3.8
          - 2.4.5
          - 2.5.3
          - 2.6.1
          - 2.7.1 
    steps: 
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: "bundle install"
      run: bundle install --jobs 4 --retry 3
    - name: "rspec"
      run: bundle exec rspec spec/
