name: "RSpec Test Suite"
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu]
        ruby:
          - 2.0.x
          - 2.1.x
          - 2.2.x
          - 2.3.x
          - 2.4.x
          - 2.5.x
          - 2.6.x
          - 2.7.x 
    steps: 
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: "bundle install"
      run: bundle install --jobs 4 --retry 3
    - name: "rspec"
      run: bundle exec rspec spec/
